### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by walterjaworski** [raphaelcorreaoct/vtex-speed-webpack#1]
Olá,
instalei o vtex-speed-webpack, inseri o nome da loja conforme a documentação e ao rodar, alguns elementos da página aparecem quebrados no navegador. No terminal a mensagem é
`Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)`

Como proceder?

**Comment by raulrios23** [comment]
@walterjaworski  did you solve the problem?
